# Generated by Django 4.2.8 on 2025-04-18 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietplan',
            name='total_carbs',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='total_fat',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='total_protein',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
    ]
