# Generated by Django 4.2.8 on 2025-04-18 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_dietplan_total_carbs_dietplan_total_fat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meal',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meal',
            name='calories',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='meal',
            name='carbs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='meal',
            name='cooking_time',
            field=models.PositiveIntegerField(default=0, help_text='Time in minutes'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='fat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='meal',
            name='ingredients',
            field=models.ManyToManyField(blank=True, through='core.MealIngredient', to='core.ingredient'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='meal_type',
            field=models.CharField(blank=True, choices=[('B', 'Breakfast'), ('L', 'Lunch'), ('D', 'Dinner'), ('S', 'Snack')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='preparation_time',
            field=models.PositiveIntegerField(default=0, help_text='Time in minutes'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='protein',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
